title: "PROPICE"
lang: fr
author:
  - name: "Dr Philippe MICHEL"
    affiliations:
      name: "Hôpital NOVO"
      department: "Unité de Soutien à la Recherche Clinique"
format:
  html:
    toc: true
    html-math-method: katex

#bibliography: stat.bib
#cite-method: biblatex
license: "MIT"
echo: false
warning: false
message: false
cache: false

